Repository sonm-io/core, pull requests merged in 2019-03, with the labels that each got.

#1859 fix: fix already fixed streaming auth
  util/xgrpc/options.go
Labels: P: high, T: bug, V: minor

#1864 fix: avoid duplicated driver volumes for GPUs
  insonmnia/worker/gpu/utils.go
Labels: P: high, S: Worker, T: bug, V: patch

#1865 fix: reduce fucking brute-force threshold for predictor
  optimus/engine.go
  optimus/predictor.go
Labels: T: bug

#1869 fix: gomod reuseport replacement
  go.mod
  go.sum
Labels: P: medium, T: refactor

#1861 fix: proper temporary errors handling in connor
  connor/engine.go
Labels: P: medium, S: Connor, T: bug
